language: java

install:
    - export main_repo_branch=$TRAVIS_BRANCH
    - echo $main_repo_branch
    - git clone https://github.com/NeuroML/org.neuroml.model.injectingplugin.git
    - cd org.neuroml.model.injectingplugin
    - git checkout $main_repo_branch
    - mvn install
    - cd ..
    - git clone https://github.com/NeuroML/org.neuroml.model
    - cd org.neuroml.model
    - git checkout $main_repo_branch
    - mvn install
    - cd ..
    - git clone https://github.com/LEMS/jLEMS.git
    - cd jLEMS
    - mvn install
    - cd ..
    - git clone https://github.com/NeuroML/org.neuroml.export
    - cd org.neuroml.export
    - mvn install
    - cd ..
    - git clone https://github.com/openworm/org.geppetto.core.git -b $TRAVIS_BRANCH
    - cd org.geppetto.core
    - git checkout tags/v0.0.9-alpha
    - mvn install
    - cd ..
    

